### ISSUE TITLE
循环到第二次shell输入完参数之后，client的请求进Server会直接触发EOF

### ISSUE THREAD

**Issue by wnz27** [HanFa/learn-go#4]
https://github.com/HanFa/learn-go/blob/25f9d2810b9c45552ef2df49f61f67bddd7ca2d4/grpc-example/route-client/client.go#L126

**Comment by huruizhi** [comment]
我也 碰到了同样的问题，请问解决了吗？

**Comment by huruizhi** [comment]
似乎在server 端 添加goroutine 可以解决
https://gitlab.cn/rzhu_projects/grpc_demo

**Comment by wnz27** [comment]
> 似乎在server 端 添加goroutine 可以解决
> https://gitlab.cn/rzhu_projects/grpc_demo

改天试下，我现在忘光了哈哈哈哈

**Comment by HanFa** [comment]
看了下 这个bug是由于server在发送后响应 直接不小心return了 导致客户EOF
